### ISSUE TITLE
Can't login.

### ISSUE THREAD

**Issue by djbneg** [rogora/hangish#1]
Hello. Whatever i try i just cannot login. Please help me out to help you troubleshoot. 2-factor, pin does not work. 
/J

**Comment by rogora** [comment]
Have you tried to use either username or email?
Do you receive the sms with the pin code?
Do you have any error written in red in the login page after you send the pin code?

**Comment by TMavica** [comment]
I cant login too, wrong username or password. send pin: login failed

**Comment by djbneg** [comment]
@rogora Both username and mail returns "login failed: https://accounts.google.com"
but that is all i can see, the rest is cut off due to ui restrictions. This happens when i press pincode button.

**Comment by ahjolinna** [comment]
I still have this exact problem, I tried username and email...I also received the sms with the pin code and I get the same error

**Comment by rogora** [comment]
Are you using the last version, 0.2-4? What error do you have exactly? Could you post your debug logs?

**Comment by ahjolinna** [comment]
I have the latest version (0.2-4), I think I could debug later today...and I get the "login failed: https://accounts.google.com" error thing

**Comment by rogora** [comment]
Do you have multiple accounts tied together, as per lukedirtwalker suggestion?

**Comment by ahjolinna** [comment]
multiple accounts? I think so...why?

**Comment by rogora** [comment]
Well, lukedirtwalker suggested with a comment on openrepos that this could be the problem.

Since I have only one Google account I can't test this case myself, but my guess is that when you authenticate, you reach a Google page where you are asked for something (which account to use maybe?) and the user should give some input.

Now, do you know if this is the case? 
Anyway, the debug log could help me somehow to figure out what happens.

**Comment by ahjolinna** [comment]
hmmm... WTF?! now it works after U11 -_- , also it seems there are some qml/silica errors with U11

**Comment by fgaz** [comment]
I'm using the lastest version (0.3.0) and the login fails with the following errors:
* `login failed: https://accounts.google.com` when I use the one-time password
* `wrong username/password` when I use an app-specific password

**Comment by rogora** [comment]
Are you using 2nd factor authentication? If so, why don't you input your pin in Hangish directly?

**Comment by fgaz** [comment]
I tried (otp = 2nd factor auth), but it produces the first error.
I am using SailOTP to generate the pin, and it works for other apps.

**Comment by rogora** [comment]
Yes please, send me your logs, and I'll try to fix this

**Comment by 127001** [comment]
Wouldn't know how to gather the logs, but have the same login issue with 0.3.0

**Comment by fgaz** [comment]
Open the terminal and type
    Hangish &> hangish.log
then try to log in and close hangish.

The log file should be in your home (`&>` redirects all output to a file)

**Comment by 127001** [comment]
Log send to [daniele.rogora AT gmail DOT com]

**Comment by rogora** [comment]
@127001  Thanks for the log, I'll try to fix this. Could you please tell me exactly what steps did you take when you got this log? 

@fgaz I'm not sure I understood how sailotp is supposed to work, but my guess is that it won't work with Hangish. 
If you use 2nd factor auth, Hangish expects you to:
- put your common email and password pair
- push login (top right corner)
- put the pin that you received (usually by sms)
- push the "Send pin" button

I understand this may not be an intuitive procedure, I'll try to make things clearer once I manage to make authentication work for everyone.

**Comment by fgaz** [comment]
Oops, my bad, sorry for reopening the issue.
I interpreted "Send pin" as "Send sms with pin to phone" instead of "Send pin to server".
Now it works without any problem, even with SailOTP, but you should definitely separate the two login phases to prevent further misunderstandings.

**Comment by rogora** [comment]
Great!
What about you, @127001 ? From your logs it seems that you did something like @fgaz

**Comment by 127001** [comment]
Ah, thanks! Indeed, I didn't try it in that specific order. I agree the issue should not have been reopened, and I agree the UI really needs to be clearer on this :-)
A new screen with only the input pin and send ping would be wiser. If you use that, you can get closer to the SailfishUI too as you can use replace 'Login' on the next screen.
