### ISSUE TITLE
Pressing Enter in the middle of a message makes it impossible to send

### ISSUE THREAD

**Issue by nodevel** [rogora/hangish#25]
When you write a message, make a mistake, go back to edit it and press Enter to send it, it will result in *Error, msg not sent!* message. This repeats until you manually delete the inserted newline character, place the cursor at the end of the message and press Enter then.

This behavior is quite annoying, as it makes typing and editing previous text much more difficult.

**Comment by rogora** [comment]
Introduced a workaround in commit 3769b4c4163f8a2f780de193fc9a791d489744a8
