### ISSUE TITLE
Hangish not receiving messages in real time

### ISSUE THREAD

**Issue by nodevel** [rogora/hangish#30]
Something must have changed during the last few days, because I am no longer able to receive messages in Hangish in real time. Messages load fine on start and also sent without a problem, but no messages get received as they arrive (so it seems like the other person is not responding). All while Hangish is the only connected Hangouts client.

When I try to log to Hangouts through the XMPP protocol, messages arrive only there. Before this suspected change, messages would arrive both to through the XMPP protocol and Hangish.

I tried to log out and back in, but without any difference. Please look into this, as it makes Hangish practically unusable.

**Comment by rogora** [comment]
Thank you for reporting this; I'm aware of the problem, caused by some updates to the older APIs by Google.

Anyway, I will hopefully fix this soon.

**Comment by rogora** [comment]
82a12dc238be49cd79c474647c1b7503dbe8d415 is the first step for this issue; now we have events back, but the parser and many otger things need to be updated accordingly.
