### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by abranson** [rogora/hangish#35]
Hangish stopped connecting a couple of days ago. The OAuth works, but it fails to connect afterwards, and on subsequent restarts:

[D] Client::pvtReply:1531 - Got  1 cookies from  QUrl( "https://talkgadget.google.com/talkgadget/_/extension-start" )
[D] Client::pvtReply:1531 - Got  0 cookies from  QUrl( "https://talkgadget.google.com/talkgadget/_/extension-start" )
[D] Client::slotError:1907 - Error in client  203
[D] Client::networkReply:504 - DBG Got  0 from  QUrl( "https://talkgadget.google.com/u/0/talkgadget/_/chat?prop=hangish&fid=gtn-roster-iframe-id&ec=[%22ci:ec%22,true,true,false]&pvt=<snip>" )

**Comment by nodevel** [comment]
Same here, thanks for the report.

Even after deleting the cookie and logging again, it shows the aforementioned error.

**Comment by lewadedun** [comment]
Same for me

**Comment by tanty** [comment]
Same here

**Comment by nodevel** [comment]
Just tested a build with the URL fix ( #38  ) from @Incognitas and it works fine. Thanks, @Incognitas !
Let's hope the push request will be merged soon.

**Comment by rogora** [comment]
Fix

**Comment by tanty** [comment]
:+1: Thanks!
