### ISSUE TITLE
High CPU usage?

### ISSUE THREAD

**Issue by GNious** [rogora/hangish#4]
App is draining battery :(

Looked at CPU usage while the app was running, to determine why battery-levels were plummeting, and found that Hangish hovered between 24 and 60% CPU usage.

Is a nice app, but this needs to be addressed.

**Comment by rogora** [comment]
I'm aware of the problem, but it happens only seldom and after connectivity changes/problems. Also, when this behavior is observed, I found that the app doesn't receive messages and you have to kill and restart the app; after this the CPU usage is back to normal levels, that is 0-1%.

I will investigate this, although I found that it is quite tricky to reproduce the scenario.

**Comment by GNious** [comment]
Uki, I'm fairly certain I was still able to receive messages after this happened, but will try to recreate the situation again and test.

**Comment by rogora** [comment]
Great, please let me know if you find out how to reproduce the behavior.

**Comment by rogora** [comment]
I couldn't reproduce the problem anymore after my commit, I consider this fixed
