### ISSUE TITLE
'Reenable notifications' not persistent

### ISSUE THREAD

**Issue by nodevel** [rogora/hangish#41]
When you Silence a contact, the silence persists over app restarts.
However, Reenabling notifications does not persist, therefore once you silence (even accidentally) a contact, it is now silenced on every start and it cannot be permanently reverted.

### How to reproduce:

1. Long tap a contact
2. Select 'Silence'
3. Long tap it again
4. Select 'Reenable notifications'
5. Close the app
6. Open the app again

### What should happen:

1. The notifications for the contact should be enabled

### What happens instead:

1. The contact is silenced instead

**Comment by rogora** [comment]
Ok thanks for reporting, I guess something has changed in the Google Hangouts protocol

**Comment by rogora** [comment]
Couldn't reproduce this; can anyone else confirm?

**Comment by lewadedun** [comment]
Couldn't reproduce this

**Comment by rogora** [comment]
Ok now I've seen this; it appears that the info about conversation status is not parsed correctly anymore, since those conversations aren't actually really silenced
