### ISSUE TITLE
Any way to use the Hangish code in C++ Qt Application?

### ISSUE THREAD

**Issue by theweavrs** [rogora/hangish#42]
I was wondering if there was a way of using Hangish Hangouts Implementation code in a C++ Qt desktop application or a QML Desktop Application. Also, a simple example would be very much appreciated.

Thank you. :+1:

**Comment by rogora** [comment]
Hi! I'm not an expert c++ programmer, so I'm not sure about the specific problems you may face, but I guess it won't be hard to port hangish to a plain Qt app.
I think you would only have to disable some of the hacks I had to implement to make it work realiably with an unreliable connection like the one you have on mobile phones... but again, I think you'll mainly have to remove stuff.
Probably you would want to rewrite the notification class to use some other low level infrastructure.
Anyway, the main interaction with hangouts goes through the Client class; in client.h you can see a nice list of public methods that you can use.
Let me know if you manage to build something.
