### ISSUE TITLE
Update on open repos please. 

### ISSUE THREAD

**Issue by kdb424** [rogora/hangish#43]
I've been trying to get this compiled, but unfortunately my Forte is python code, not really compiled languages. Any chance you could update open repos or post a binary here for those lacking a proper dev environment? If not, totally understandable. Thanks for all of your effort and making sailfish a more useful os for my phone. Do you have a place to donate?

**Comment by rogora** [comment]
Hello, thank you for your support.
You can download the binaries for hangish directly from the Jolla store; why do you want me to publish it also on Openrepos?
Anyway, I did accept donations through paypal (there's a direct link in the application) and from flattr, but at this time I'm not working anymore actively on hangish..

**Comment by kdb424** [comment]
I am currently working on Sailfish development using a custom ROM for my oneplus one so unfortunately until I get access to an official phone, I won't have access to the Jolla store, nor do anyone else that want to support the OS but don't have an official phone. I'm currently judging to see if Sailfish can replace Android for myself and if so purchase an official phone, but this is one of the last things I wanted to test before I actually purchased something official to dev on. Thank you for your swift response.

**Comment by lewadedun** [comment]
+1
24 июня 2016 г. 19:17 пользователь "Kyle Brown" <notifications@github.com>
написал:

**Comment by rogora** [comment]
Ok, your request makes sense. I have updated the OpenRepos page.

**Comment by kdb424** [comment]
Thank you so much.
