### ISSUE TITLE
Problem with authentication process

### ISSUE THREAD

**Issue by eohulse** [rogora/hangish#44]
I deleted my token this morning, but could not obtain a new one anymore. Now when I start hangish I'm redirected to a page with an error message:
Error: invalid_scope
Not authorized to request scopes: [https://www.google.com/accounts/OAuthLogin]

Apparently this issue is happening for a week, with other third party apps that try to connect to google hangouts (https://productforums.google.com/forum/m/%23!topic/hangouts/LU2YZNDhN_s&sa=U&ved=0ahUKEwjdlNvfvYXPAhVIC5AKHYO6ATgQFggLMAA&usg=AFQjCNGDOVg9FO_L9foCBuKrsmac_vxBlA)
It seems that the scope has to be changed... For now it is better not to delete the token as I did.

**Comment by eohulse** [comment]
the link above is bad, this is one should work, https://productforums.google.com/forum/m/#!topic/hangouts/LU2YZNDhN_s

**Comment by rogora** [comment]
Thanks for reporting this. I'm afraid I don't have time to look for a solution to this problem, but if any solution is found, I'll be happy to update hangish.

In the meantime, if you want to continue using hangish, I suggest you to get an authentication cookie with your computer, and create the authentication cookie for hangish yourself.

**Comment by abranson** [comment]
Does the new version fix this? It's definitely fixed my conversations list. Thanks!

**Comment by rogora** [comment]
I'm afraid it doesn't. I haven't had time to work on this yet

**Comment by eohulse** [comment]
I managed to get an authentication cookie, but could you advise me on how should I format the file to place it and also where should I place it within the sailfish file system?  Thanks!

PS: Apparently some are using an workaround to get through the authentication process. [https://github.com/tdryer/hangups/issues/260#issuecomment-246578670]

**Comment by rogora** [comment]
Should be fixed with the latest version. Let me know if you cannot authenticate with the new procedure

**Comment by abranson** [comment]
I get "Error L3" when trying to log in

**Comment by rogora** [comment]
Thank you very much for trying. Apparently you get an error code from Google when you send your credentials. 
I was afraid this kind of errors could arise dropping the webview authentication, but unfortunately Sailfish doesn't allow for anything simpler.

Would you mind helping me debugging this issue trying a debug version of hangish and sending me the (obfuscated) logs?

**Comment by abranson** [comment]
No problem at all. It might be an idea to try the new Gecko Webview in Sailfish when that's ready - maybe that won't suffer from this ban.

**Comment by rogora** [comment]
Could you send me your email address?
