### ISSUE TITLE
New messages no longer shown

### ISSUE THREAD

**Issue by lukedirtwalker** [rogora/hangish#5]
Somehow I can't see new message on Hangish, while I see them in Hangouts. Also one Conversation is completely gone. I was using 0.2.6b

Seems like the protocol changed again?

**Comment by rogora** [comment]
Well it can be, but everything is still fine here. Can anyone else confirm?

**Comment by lukedirtwalker** [comment]
({key: 'ds:2', isError:  false , hash: '20', data:function(){return [["cin:acc","","v1",,"1423613698","wcs","chat_wcs_20150209.135845_RC3",3]

there seems to be the date 2015 02 09 ? If that is the protocol version

**Comment by lukedirtwalker** [comment]
Hm it seems that things should still work, but I screwed up the whole parsing by sending a single character: [ 
I'm investigating this issue and try to find a fix.
