### ISSUE TITLE
Contacts are all named "User not found 2"

### ISSUE THREAD

**Issue by larstiq** [rogora/hangish#50]
Since all conversations are either "User not found 2" or "User not found 2, User not found2, ..." for mult user chats, you have to judge from conversation ordering or by looking at the actual messages who you are talking to.

**Comment by larstiq** [comment]
Aha, after restarting Hangish, the contacts do have names and pictures. So I guess this is an initial login thing, missing some call to populate the roster?

**Comment by rogora** [comment]
Well, I also noticed this problem yesterday, for a couple of hours. Don't know whether it was a temporary problem with Google services, or an update rolling out.

In the meantime, I close the issue.
