### ISSUE TITLE
no more inbound message after a while

### ISSUE THREAD

**Issue by akm1970** [rogora/hangish#51]
hi,

am using the 0.9 version from Jolla store.
After about a day or 2 it no longer gets new incoming messages, I can still send message without issue and they show up when I check on the hangout website but new message are not displayed.
I need to logout and login again. (for that would it be possible to remember user/pwd) ?

If there are any logs or things you need when this happens let me know.

**Comment by rogora** [comment]
I also noticed the problem, and I'm trying to understand it. It really seems to be related to the new qt libraries brought by sailfish 2.1.
The connection drops also when you switch from mobile to wifi connection. As a workaround, you can put your phone in flight mode, and then back to normal.

Also, if you "log out" from the menu, the authentication token is deleted, but if you close hangish as you would with any other application, the authentication token is kept on your file system, and you won't need to login again the next time.

**Comment by akm1970** [comment]
thank for you answer, I will try the solution of closing and re-opening next time it happens.
I do notice that message I send during that time do arrive on google but remain as "sent" instead of the time underneath it.

If anything I can do let me know.

**Comment by rogora** [comment]
I pushed a workaround for this with version 0.9.1, let me know if you can still reproduce the problem with that.
