### ISSUE TITLE
Crashes on login

### ISSUE THREAD

**Issue by abranson** [rogora/hangish#7]
My Hangish client stopped logging in automatically, and it crashes when I try to log back in. If I run Hangish from the command-line, I see it manage to log in, followed by a long string of JSON containing all the latest messages from everyone, but then it spits out:

}});</script>"
[D] Client::networkReply:428 - 200
[D] Client::networkReply:430 - Auth expired!

Any ideas? Is there any message content that can crash Hangish?

**Comment by rogora** [comment]
Thanks for the report; I think that Hangish is not really crashing, but it thinks that your authentication is expired.
Should a stupid bug introduced in the first experiments with the Hangouts api, should be a simple fix, I'll push it asap.
Could you please post your Client::networkReply:428 line, to confirm my idea?

**Comment by abranson** [comment]
428 is in my original comment, it was '200'
I have: 
Client::networkReply:399 - DBG Got  0 from  QUrl( ...
Client::networkReply:425 - API KEY:
and a
Client::networkReply:427 - "<script>var AF_initDataKeys...

Any of those?

**Comment by rogora** [comment]
Ok so this is not the trivial stuff I thought, since you really don't have a valid api key; seems like a parsing problem... are you using version 0.2.6b? Could you try version 0.2.6?

**Comment by abranson** [comment]
Sorry, have an api key. I just truncated those lines so as not to post any keys in case they should be kept secure. 427 is a good couple of thousand lines of JSON. The API Key is there: it's a 39 char string. I'm on 0.2.6b, but tried it on 0.2.6 yesterday with the same behaviour.

Sorry again for the misleading post!
