### ISSUE TITLE
Fails to retrieve all contacts

### ISSUE THREAD

**Issue by purplewakanda** [rogora/hangish#9]
I see only some of my contacts displayed. A lot of them are missing. Among the listed contacts many are displayed as "User not found" but clicking on those the chat history is available.

![screenshot-22-04-15-11-05-14](https://cloud.githubusercontent.com/assets/12062072/7267934/3db3f2d0-e8e0-11e4-9b5d-c08ae8d95536.png)

**Comment by rogora** [comment]
Well, those are conversations, not contacts.
Since the possibility to open new conversations has not been added yet, there's not any way of viewing all your contacts now. 
Now, regarding the User not found: are those people subscribed to Google+? Have you created the conversations with them by their mobile phone number?

**Comment by purplewakanda** [comment]
Okay. I'm not sure if they are subscribed to Google+. I've not created the conversations with them by using their mobile phone number. Is that an issue?

**Comment by rogora** [comment]
So, where and how have you created those conversations? On your IOS/Android mobile phone, with a computer?
Do you correctly see the names with the other applications?

**Comment by purplewakanda** [comment]
I've created those on my computer and the native chat app on Jolla. I do see the correct names on my computer and phone.

**Comment by lukedirtwalker** [comment]
@purplewakanda I wonder if that still happens with the latest version ?

**Comment by purplewakanda** [comment]
Yes, its the same with the latest version.

**Comment by tuomo** [comment]
I think this has something to do with having people in your circles in Google+. The problem disappeared for one of my contacts when I added them to a circle.

**Comment by rogora** [comment]
Thanks for helping with this; unfortunately I don't think that circles are the actual problem, but I'll try to figure it out.

**Comment by rogora** [comment]
Not closed yet
